# Generated by Django 5.0.3 on 2024-08-01 03:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_bankaccount_created_at_bankaccount_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_account_number', models.CharField(max_length=20)),
                ('receiver_account_number', models.CharField(max_length=20)),
                ('sender_username', models.CharField(max_length=150)),
                ('receiver_username', models.CharField(max_length=150)),
                ('amount_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_after_sender', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_after_receiver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.transfer')),
            ],
            options={
                'verbose_name': 'Transfer Audit',
                'verbose_name_plural': 'Transfer Audits',
            },
        ),
    ]
