# Generated by Django 5.0.3 on 2024-08-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_is_active_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='concept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
