# Generated by Django 5.0.3 on 2024-08-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_transfer_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
